# Generated by Django 3.0.5 on 2020-04-25 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('categoria', models.CharField(max_length=40)),
                ('marca', models.CharField(max_length=40)),
                ('fecha_v', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('dni', models.IntegerField()),
                ('id_p', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='venta.producto')),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('correo', models.TextField()),
                ('telefono', models.IntegerField()),
                ('direccion', models.TextField()),
                ('id_p', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='venta.producto')),
            ],
        ),
    ]
