# Generated by Django 3.0.5 on 2020-04-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_auto_20200426_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='id_p',
        ),
    ]
