# Generated by Django 3.0.5 on 2020-04-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_remove_vendedor_id_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='dni',
            field=models.BigIntegerField(),
        ),
    ]
